export default class AppScreens {

    public static OnboardingStack = 'OnboardingStack'
    public static ApplicationStack = 'ApplicationStack'
    public static Gambling_OnboardingStack = 'Gambling_OnboardingStack'
    public static Gambling_ApplicationStack = 'Gambling_ApplicationStack'
    public static LoggedOutStack = 'loggedOutStack'
    public static AgeConfirmation = 'AgeConfirmation'
    public static LocationConfirmation = 'LocationConfirmation'
    public static LoginPage = 'LoginPage'
    public static RegistrationPage = 'RegistrationPage'
    public static ProfileView = 'ProfileView'
    public static VerifyOTPView = 'VerifyOTPView'
    public static DashboardView = 'DashboardView'
    public static SettingsView = 'SettingsView'
    public static Settings_2_View = 'Settings_2_View'
    public static AddMoneyView = 'AddMoneyView'//03-05-2019(Anjali)
    public static WithdrawMoneyView = 'WithdrawMoneyView'//03-05-2019(Anjali)
    public static Highlighted_Matchups_View = 'Highlighted_Matchups_View'//06-05-2019(Anjali)
    public static MostOpenActionView = 'MostOpenActionView' //06-05-2019(Pooja)
    public static OpenPlaysView = 'OpenPlaysView' //08-05-2019(Pooja)
    public static SplashMain = 'SplashMain' //08-05-2019(Pooja)
    public static HistoryView = 'HistoryView' //27-05-219(Pooja)
    public static GameCastView = 'GameCastView'//Anjali(22-05-2019)
    public static FAQView = 'FAQView'//Anjali(27-05-2019)
    public static CoveredPlaysView = 'CoveredPlaysView' //Pooja(03-06-2019)
    public static TermsOfUseView = 'TermsOfUseView' //Pooja(03-06-2019)
    public static PrivacyPolicyView = 'PrivacyPolicyView' //Pooja(03-06-2019)
    public static PrivateBetView = 'PrivateBetView' //Anjali(08-06-2019)
    public static PrivateBetMessgesView = 'PrivateBetMessgesView' //Anjali(08-06-2019)
    public static LandingView = 'LandingView' //Anjali(08-06-2019)
    public static SplashLandingView = 'SplashLandingView'
    public static MyFavoriteView = 'MyFavoriteView'

    //Phase 2 Gambling Pooja (11-07-2019)
    public static G_AgeConfirmation = 'G_AgeConfirmation'
    public static G_LocationConfirmation = 'G_LocationConfirmation'
    public static G_LoginPage = 'G_LoginPage'
    public static G_RegistrationView = 'G_RegistrationView'
    public static G_ForgotPassword = 'G_ForgotPassword'
    // public static G_ProfileView = 'G_ProfileView'
    public static G_VerifyOTPView = 'G_VerifyOTPView'
    public static G_DashboardView = 'G_DashboardView' //(12-07-2019) Pooja
    public static G_SettingsView = 'G_SettingsView' //(12-07-2019) Pooja
    public static G_Highlighted_Matchups_View = 'G_Highlighted_Matchups_View' //(13-07-2019) Pooja
    public static G_MostOpenActionView = 'G_MostOpenActionView' //(13-07-2019) Pooja
    public static G_CoveredPlaysView = 'G_CoveredPlaysView' //(13-07-2019) Pooja
    public static G_FAQView = 'G_FAQView' //(13-07-2019) Pooja
    public static G_ProfileView = 'G_ProfileView' //(13-07-2019) Pooja
    public static G_OpenPlaysView = 'G_OpenPlaysView'
    public static G_PrivateBetView = 'G_PrivateBetView'
    public static G_HistoryView = 'G_HistoryView'
    public static G_TermsOfUseView = 'G_TermsOfUseView'
    public static G_PrivacyPolicyView = 'G_PrivacyPolicyView'
    public static G_PrivateBetMessgesView = 'G_PrivateBetMessgesView'
    public static G_AddMoneyView = 'G_AddMoneyView'
    public static G_WithdrawMoneyView = 'G_WithdrawMoneyView'
    public static G_MyFavoriteView = 'G_MyFavoriteView'
    public static G_GamingBetView = 'G_GamingBetView'
    public static G_Settings_2_View = 'G_Settings_2_View'
    public static G_RedeemUddaBucks = 'G_RedeemUddaBucks'//anjali 23-08-2019
    public static G_UddaContests = 'G_UddaContests'//anjali 27-08-2019
    public static G_StandingList = 'G_StandingList'//anjali 28-08-2019
    public static G_PrivateContest = 'G_PrivateContest'//anjali 30-08-2019
    public static G_QuickGuide = 'G_QuickGuide'//anjali 04-09-2019
    public static G_ContestDashboardView = 'G_ContestDashboardView'//anjali 17-09-2019
    // public static G_YourPrivateContest = 'G_YourPrivateContest'//anjali 14-10-2019
    public static G_RedeemHistory = 'G_RedeemHistory'//anjali 15-10-2019
    public static G_InvitationToJoin = 'G_InvitationToJoin'//anjali 15-10-2019
    public static G_PrivateContestUserView = 'G_PrivateContestUserView'//anjali 15-10-2019
    public static G_TransactionHistoryView = 'G_TransactionHistoryView'//anjali 15-10-2019
    public static G_InAPPPurchaseView = 'G_InAPPPurchaseView'//anjali 15-10-2019
    public static G_InAPPSubscriptionView = 'G_InAPPSubscriptionView'//anjali 07-11-2019
    public static G_OnlyTermsOfUseView = 'G_OnlyTermsOfUseView' //Pooja(04-10-2019)
    public static G_OnlyPrivacyPolicyView = 'G_OnlyPrivacyPolicyView' //Pooja(04-10-2019)
    public static G_FAQ_QuickGuide = 'G_FAQ_QuickGuide' //Anjali(19-11-2019)
    public static G_ResetPassword = 'G_ResetPassword' //Anjali(20-11-2019)
    public static G_InfochartView = 'G_InfochartView' //Anjali(11-12-2019)
    public static G_ReferEarnView = 'G_ReferEarnView' //garima
    public static G_InAPPSubscriptionViewIOS = 'G_InAPPSubscriptionViewIOS'//vijay 11-03-2019
    public static G_InAPPPurchaseViewIOS = 'G_InAPPPurchaseViewIOS'//vijay 12-03-2019
	public static G_VerifyForgotOTPView = 'G_VerifyForgotOTPView'
	public static G_CustomBet = 'G_CustomBet'//ashish
    public static G_CustomBetResult = 'G_CustomBetResult'//ashish
    public static G_Createpool = 'G_Createpool'//ashish
	public static G_Settlepool = 'G_Settlepool'//ashish
    public static G_ImageZoom = 'G_ImageZoom'//ashish
    // public static G_SettleSquare = 'G_SettleSquare'//ashish
    // public static G_SquareBoard = 'G_SquareBoard'//ashish
    // public static G_AcceptSquare = 'G_AcceptSquare'//ashish
    public static G_ZoomSquare = 'G_ZoomSquare'//ashish
    public static G_ContestviewSquare = 'G_ContestviewSquare'//ashish
    public static G_MyLeagueOrderView = 'G_MyLeagueOrderView'
    public static G_CreateSquareView = 'G_CreateSquareView'
    public static G_SelectGameView = 'G_SelectGameView'
    public static G_AcceptSquare = 'G_AcceptSquare'
    public static G_SquareBoard = 'G_SquareBoard'
    public static G_SettleSquare = 'G_SettleSquare'
    public static G_SettlePoolInfoView = 'G_SettlePoolInfoView'
    public static G_AgreeDisagreeInfoView = 'G_AgreeDisagreeInfoView'
    public static G_NotificationView = 'G_NotificationView' //sunidhi
    public static G_InAppPurchaseUpdateIOS = 'G_InAppPurchaseUpdateIOS' //sunidhi
    public static G_MyRefereesView = 'G_MyRefereesView' //sunidhi
    public static G_ParticipantList = 'G_ParticipantList' //Ashish
    public static G_CounterCustomBet = 'G_CounterCustomBet' //vijay
    public static G_CreateBingo = 'G_CreateBingo' //Ashish
    public static G_SquareGift = 'G_SquareGift' //Ashish
    public static G_AcceptBingo = 'G_AcceptBingo' //Ashish
    public static G_ShareBingo = 'G_ShareBingo' //Ashish
    public static G_contestBingo = 'G_contestBingo' //Ashish
    public static G_Spinner = 'G_Spinner' //Ashish
    public static G_VideoList = 'G_VideoList' //Ashish
    public static G_Yotube = 'G_Yotube' //Ashish
    public static G_Notify = 'G_Notify' //G_Notify
    public static G_BetInfo = 'G_BetInfo' //Ashish
    public static G_Scaner = 'G_Scaner'
    public static G_SummaryNotificationView = 'G_SummaryNotificationView'
    public static G_FtpCurrentStanding = 'G_FtpCurrentStanding'
    public static G_FtpContestDashboard = 'G_FtpContestDashboard'
    public static G_SpinnerPurchase = 'G_SpinnerPurchase'
}