import AppUtil from "../../../../Util";
import UrlService from '../../../../Services/Core/ServiceURI'

export const playTableWeek = 
{
    "error": 0,
    "version": "1.0",
    "message": "success",
    "data": {
        "bet_detail": {
            "bet_id": "6",
            "user_id": "79",
            "event_id": "946687",
            "league_id": "1",
            "bet_odds_type": "1",
            "bet_type": "1",
            "bet_amount": "20.00",
            "amount_to_win": "57.00",
            "bet_team_type": "underdog",
            "bet_team_id": "5",
            "wining_rate_favored": "1.53",
            "wining_rate_underdog": "2.88",
            "odds_id": "607",
            "lookup": "946687:1:13",
            "period_id": "1",
            "period_name": "FG",
            "total": "46",
            "total_under_price": "-120",
            "total_over_price": "120",
            "total_draw_price": "",
            "ps_away_spread": "4",
            "ps_away_price": "",
            "ps_home_spread": "-4",
            "ps_home_price": "",
            "ps_draw_spread": "",
            "ps_draw_price": "",
            "ml_away_price": "188",
            "ml_home_price": "-188",
            "ml_draw_price": "",
            "bet_type_id": "13",
            "alt_id": "0",
            "bet_on": "0",
            "is_confirm": "1",
            "remain_amount_win": "0.00",
            "created_at": "May 22, 2019, 10:51 AM",
            "reject_date": null,
            "event_name": "Packers Vs Bears",
            "total_people": "0",
            "total_people_amount": null
        },
        "bet_user_info": {
            "id": "79",
            "firstname": "bhavin",
            "lastname": "jagad",
            "email": "jagad007@gmail.com",
            "phone": "76524729021",
            "password": null,
            "fb_id": null,
            "twitter_id": null,
            "google_id": "103117137283137735196",
            "photo": UrlService.CONSTURI +"index.php/assets/photos/default-user.jpg",
            "latitude": "22.31069600",
            "longitude": "73.19263500",
            "otp": null,
            "device_type": "ios",
            "device_token": "",
            "access_token": "76C4qw9UDmr35zuqF6PIM8vE1YRfHZk2oyzIVydEnGlFjrOiADsAbhCHGS8vtT0L",
            "verified": "1",
            "status": "1",
            "balance": "7378.58",
            "updated_at": "2019-05-17 09:25:26",
            "created_at": "2019-04-12 11:48:42"
        },
        "people_list": [],
        "opposite": {
            "question": "Bhavin Jagad placed $20.00 on -188 (Money Line), Will you accept the bet?",
            "name": "Bhavin Jagad",
            "amount": "$20.00",
            "odds": "-188 (Money Line)",
            "answer": "Favored  "
        },
        "available_betamount": 20
    }
}